baseURL = "https://www.qikqiak.com/"
languageCode = "en-us"
title = "阳明的博客"
theme = "beautifulhugo"
canonifyURLs = true
DefaultContentLanguage = "zh"
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "dracula"
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = false
paginate = 12
googleAnalytics = "UA-69668147-3"
autoFigure = true

[params]
  subtitle = "关注 ChatGPT、Kubernetes、Istio、DevOps、Prometheus、Python、Golang、云原生、微服务等技术"
  keywords = "chatgpt、docker、kubernetes、istio、devops、prometheus、python、golang、云原生、微服务"
  author = "阳明"
  navLogo = "https://picdn.youdianzhishi.com/images/blog-logo-new.png"
  logo = "https://picdn.youdianzhishi.com/images/blog-favicon.png"
  avatar = "https://picdn.youdianzhishi.com/images/blog-favicon.png"
  favicon = "https://picdn.youdianzhishi.com/images/blog-favicon.png"
  rss = true
  reward = true
  algolia = "8804ac109158bb3bb60d74ce98fa332f" # API key
  useWebfont = true
  customCSSAssets = []
  customJSAssets = []
  defaultImg = "https://picdn.youdianzhishi.com/images/photo-1557380664-dd666ff4e559.jpeg"

[params.adsense]
  client = "ca-pub-5376999672787220"
  inArticleSlot = "5684687044"
  textSlot = "9165834656"

[params.gitcomment]
  owner = "cnych"
  repo = "blog"
  clientId = "bdb76dbb2e9d0786e350"
  clientSecret = "b454b2a08013fd0e32013be7a63fa8fcb262b6c4"

# [[params.banner]]
#   src = "https://picdn.youdianzhishi.com/images/k8s-banner-k8scourse.jpg"
#   desc = "打造独当一面的 Kubernetes 运维、开发工程师"
#   url = "/post/promotion-51/"

[[params.banner]]
  src = "https://picdn.youdianzhishi.com/images/aliyun-cloudnative-edu1.jpeg"
  desc = "云原生技术公开课"
  url = "https://edu.aliyun.com/roadmap/cloudnative?spm=a1z389.11499242.0.0.65452413qdXfZ7&utm_content=g_1000093512"

[[params.banner]]
  src = "https://picdn.youdianzhishi.com/images/k8s-banner-ydzs.jpg"
  desc = "优点知识"
  url = "https://youdianzhishi.com/?utm_source=blog&utm_campaign=referral&utm_medium=banner"

[[params.banner]]
  src = "https://picdn.youdianzhishi.com/images/k8s-banner-promebook.jpg"
  desc = "《深入浅出 Prometheus》"
  url = "https://detail.tmall.com/item.htm?spm=a212k0.12153887.0.0.64a3687dQ6nSzh&id=590161370307"

# [[params.bigimg]]
#   src = "img/golang-k8s.png"
#   desc = ""
#   position = "center top"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "course"
    name = "课程"
    weight = 2
    url = "https://youdianzhishi.com/?utm_source=blog&utm_campaign=referral&utm_medium=topmenu"

[[menu.main]]
    identifier = "categories"
    name = "文章分类"
    weight = 3

[[menu.main]]
    parent = "categories"
    name = "Archive"
    url = "archives"
    weight = 1

[[menu.main]]
    parent = "categories"
    name = "tags"
    url = "tags"
    weight = 1

[[menu.main]]
    parent = "categories"
    name = "kubernetes"
    url = "tags/kubernetes"
    weight = 2

[[menu.main]]
    parent = "categories"
    name = "python"
    url = "tags/python"
    weight = 3

[[menu.main]]
    parent = "categories"
    name = "django"
    url = "tags/django"
    weight = 4

[[menu.main]]
    parent = "categories"
    name = "devops"
    url = "tags/devops"
    weight = 5

[[menu.main]]
    identifier = "book"
    name = "书籍"
    weight = 4


[[menu.main]]
    parent = "book"
    name = "k8s进阶手册"
    url = "/k8s-book/"
    weight = 1

[[menu.main]]
    parent = "book"
    name = "一起学istio"
    url = "/istio-book/"
    weight = 2

[[menu.main]]
    parent = "book"
    name = "Python微服务"
    url = "/tdd-book/"
    weight = 3

[[menu.main]]
    parent = "book"
    name = "Markdown微信"
    url = "https://md.qikqiak.com/"
    weight = 4

[[menu.main]]
    name = "关于"
    url = "page/about/"
    weight = 5

[[menu.main]]
    name = "RSS"
    url = "index.xml"
    weight = 6