baseURL = "https://www.qikqiak.com/"
languageCode = "en-us"
title = "阳明的博客"
theme = "beautifulhugo"
canonifyURLs = true
DefaultContentLanguage = "en"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-69668147-3"

[params]
  subtitle = "关注容器、kubernetes、istio、devops、python、golang等~~~"
  keywords = "关注容器、kubernetes、istio、devops、python、golang等"
  author = "阳明"
  logo = "img/avatar.jpeg"
  favicon = "img/favicon.ico"
  rss = true
  reward = true
  algolia = "8804ac109158bb3bb60d74ce98fa332f" # API key

[[params.bigimg]]
  src = "img/golang-k8s.png"
  desc = ""
  position = "center top"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    weight = 3

[[menu.main]]
    parent = "categories"
    name = "Archive"
    url = "page/archive/"
    weight = 1

[[menu.main]]
    parent = "categories"
    name = "tags"
    url = "tags"
    weight = 1

[[menu.main]]
    parent = "categories"
    name = "kubernetes"
    url = "tags/kubernetes"
    weight = 2

[[menu.main]]
    parent = "categories"
    name = "python"
    url = "tags/python"
    weight = 3

[[menu.main]]
    parent = "categories"
    name = "django"
    url = "tags/django"
    weight = 4

[[menu.main]]
    parent = "categories"
    name = "devops"
    url = "tags/ops"
    weight = 5

[[menu.main]]
    identifier = "projects"
    name = "projects"
    weight = 4

[[menu.main]]
    parent = "projects"
    name = "优点知识"
    url = "https://youdianzhishi.com/?utm_source=blog&utm_campaign=referral&utm_medium=topmenu"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "k8s进阶手册"
    url = "/k8s-book/"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "我们一起学istio"
    url = "/istio-book/"
    weight = 3

[[menu.main]]
    parent = "projects"
    name = "Python微服务实战"
    url = "/tdd-book/"
    weight = 4

[[menu.main]]
    parent = "projects"
    name = "Markdown转微信"
    url = "https://md.qikqiak.com/"
    weight = 5

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5
